# fly.toml app configuration file generated for deepstream-io-public on 2026-03-12T23:03:53Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'deepstream-io-public'
primary_region = 'gru'

[build]

[http_service]
  internal_port = 6020
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
